/*

Essas tabelas foram projetadas para organizar e relacionar os dados de recursos humanos de forma eficiente.
Cada tabela possui uma chave primária (PRIMARY KEY) que é o EMPLOYEE_ID, garantindo a integridade referencial com a tabela EMPLOYEES. 
Isso facilitará a análise e extração de insights através de ferramentas como o Power BI, permitindo uma visualização clara e detalhada das informações dos funcionários da empresa.

*/

use Recursos_Humanos
go


SELECT DISTINCT *
FROM Camada_bruta

CREATE TABLE EMPLOYEES

(
  EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
  AGE INT NOT NULL,
  GENDER VARCHAR (15) NOT NULL,
  MARITAL_STATUS VARCHAR (20) NOT NULL,
  OVERTIME VARCHAR (5) NOT NULL,
  EDUCATION VARCHAR (20) NOT NULL,
  EDUCATION_FIELD VARCHAR (50) NOT NULL,
  ATTRITION VARCHAR (3) NOT NULL

);

CREATE TABLE JOBS

(
  JOB_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
  EMPLOYEE_ID INT NOT NULL,
  JOB_ROLE VARCHAR (50) NOT NULL,
  JOB_LEVEL INT NOT NULL

  CONSTRAINT FK_JB FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)

  );


CREATE TABLE DEPARTAMENTS
(
 DEPARTAMENT_ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
 EMPLOYEE_ID INT NOT NULL,
 DEPARTAMENT VARCHAR (50) NOT NULL,
 BUSINESS_TRAVEL VARCHAR (20) NOT NULL

 CONSTRAINT FK_DP FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)

);

CREATE TABLE SALARIES
(
 EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
 MONTHLY_INCOME DECIMAL(10, 2),
 MONTHLY_RATE DECIMAL(10, 2),
 DAILY_RATE DECIMAL(10, 2),
 HOURLY_RATE DECIMAL(10, 2),
 PERCENT_SAL_HIKE DECIMAL (10,2)
    
CONSTRAINT FK_SL FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);



CREATE TABLE SATISFACTION
(
 EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
 ENVIRONMENT VARCHAR (15) NOT NULL,
 REALATIONSHIP VARCHAR (15) NOT NULL,
 JOB_SATISFACTION VARCHAR (15) NOT NULL,
 JOB_INVOLVEMENT VARCHAR (15) NOT NULL,
 WORKLIFE_BALANCE VARCHAR (15) NOT NULL,
 PERFORMANCE_RATING VARCHAR (15) NOT NULL,

 CONSTRAINT FK_SF FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID) 
);


CREATE TABLE WORK_HISTORY
(
 EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
 NUM_COMPANIES_WORKED INT NOT NULL,
 YEARS_AT_COMPANY INT NOT NULL,
 YEARSINCURRENTROLE INT NOT NULL,
 YEARS_SINCE_LAST_PROMOTION INT NOT NULL,
 YEARS_WITH_CURRMANAGER INT NOT NULL,
 TRAINING_TIMES_LASTYEAR INT NOT NULL,
 DISTANCE_FROM_HOME INT NOT NULL,
 TOTAL_WORKING_YEARS INT NOT NULL,

 CONSTRAINT FK_WH FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID) 
);


SELECT * FROM JOBS